version: '3.8'

# For local development only
services:
  gitlabkit-runner-admin:
    image: gitlabkit-runner-admin
    build:
      context: .
      dockerfile: GitLabKit.Runner.Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80:80"

  redis:
    image: redis
    ports:
      - "16379:6379"
