version: '3.8'

# For local development only
services:
  gitlabkit-runner-admin:
    image: gitlabkit-runner-admin
    build:
      context: .
      dockerfile: GitLabKit.Runner.Web/Dockerfile
    environment:
      - CONNECTIONS__GITLABSERVER=http://gitlab-mock:80
      - CONNECTIONS__REDISSERVER=redis:6379
      - SECRETS__GITLABTOKEN=aaaaaaaaaaaaaaaaaaaa
    ports:
      - "8888:80"

  gitlab-mock:
    image: gitlab-mock
    build:
      context: .
      dockerfile: GitLabKit.Runner.Mock/Dockerfile
    ports:
      - "9999:80"

  redis:
    image: redis
    ports:
      - "16379:6379"
