version: '3.8'

# For local development only
# See ops/* for k8s deployment configs
services:
  gitlab-runner-admin:
    image: gitlab-runner-admin
    build:
      context: .
      dockerfile: GitLabKit.Runner.Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "58687:80"

  redis:
    image: redis
    ports:
      - "16379:6379"
