name: "[Runner Admin] Build & Publish docker image"

on:
  push:
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: encx/gitlabkit-runner
  PUSH: ${{ github.event_name != 'pull_request' }}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.IMAGE_NAME }}
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=ref,event=pr
          type=sha
        labels: |
          org.opencontainers.image.title=GitLabKit Runner
          org.opencontainers.image.description=Tools for GitLab to help you visualize and manage self-hosted runners with ease
          org.opencontainers.image.licenses=MIT

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: src
        file: src/GitLabKit.Runner.Web/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}