name: "[Runner Admin] Release"

on:
  push:
    branches: [ main ]

jobs:

  release:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build . --file GitLabKit.Runner.Web/Dockerfile --tag my-image-name:$(date +%s)
